[project]
name = "analysis"
version = "0.1.0"
description = "Script module for automated performance analysis"
readme = "../README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.13.0",
]
